const API_KEY = process.env.REACT_APP_API_KEY
const API_URL = process.env.REACT_APP_API_URL;

const GRANT_TYPE = process.env.REACT_APP_GRANT_TYPE
const CLIENT_ID = process.env.REACT_APP_CLIENT_ID
const CLIENT_SECRET = process.env.REACT_APP_CLIENT_SECRET
const SCOPE = process.env.REACT_APP_SCOPE
const USERNAME = process.env.REACT_APP_USERNAME
const PASSWORD = process.env.REACT_APP_PASSWORD
const SHOP_URL = process.env.REACT_APP_SHOP_URL
const OAUTH_TOKEN_URL = process.env.REACT_APP_SHOP_OAUTH_TOKEN_URL
const API_PRODUCTS = process.env.REACT_APP_SHOP_API_PRODUCTS
const API_PRODUCT = process.env.REACT_APP_SHOP_API_PRODUCT
const API_USER = process.env.REACT_APP_SHOP_API_USER
const API_CREATE_ORDER = process.env.REACT_APP_SHOP_API_CREATE_ORDER

export  {
   API_KEY,
   API_URL,
   GRANT_TYPE,
   CLIENT_ID,
   CLIENT_SECRET,
   SCOPE,
   USERNAME,
   PASSWORD,
   SHOP_URL,
   OAUTH_TOKEN_URL,
   API_PRODUCTS,
   API_PRODUCT,
   API_USER,
   API_CREATE_ORDER
}